In [1]:
#!pip install --upgrade scikit-learn

# Análise com classes desbalanceadas

Breast Cancer

In [2]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.datasets import load_breast_cancer

In [2]:
X, y = load_breast_cancer(return_X_y=True, as_frame=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

NameError: name 'load_breast_cancer' is not defined

In [3]:
X_train.shape, y_train.shape

NameError: name 'X_train' is not defined

In [ ]:
X_test.shape, y_test.shape

((114, 30), (114,))

In [ ]:
X_train

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
68         9.029         17.33  ...          0.4228                  0.11750
181       21.090         26.57  ...          0.4098                  0.12840
63         9.173         13.86  ...          0.3282                  0.08490
248       10.650         25.22  ...          0.3409                  0.08147
60        10.170         14.88  ...          0.3557                  0.08020
..           ...           ...  ...             ...                      ...
71         8.888         14.64  ...          0.2254                  0.10840
106       11.640         18.33  ...          0.2806                  0.09097
270       14.290         16.82  ...          0.2458                  0.06120
435       13.980         19.62  ...          0.3179                  0.10550
102       12.180         20.52  ...          0.2694                  0.06878

[455 rows x 30 columns]

In [ ]:
# 357 benigno (1) e 212 maligno (0)
y.value_counts()

1    357
0    212
Name: target, dtype: int64

In [ ]:
clf = LogisticRegression(C=1.0, max_iter=3000).fit(X_train, y_train)
clf.score(X_test, y_test)

0.956140350877193

In [ ]:
metrics.f1_score(y_test, clf.predict(X_test))

0.9655172413793103

In [ ]:
import numpy as np
np.unique(clf.predict(X_test), return_counts=True)

(array([0, 1]), array([40, 74]))

In [ ]:
# 5-fold
scores = cross_val_score(clf, X, y, cv=5, scoring='f1_weighted')
scores

array([0.93731845, 0.94710735, 0.98245614, 0.92982456, 0.95603761])

In [ ]:
print(f"Accuracy: {scores.mean():.3} (+/- {scores.std() * 2:.3})")

Accuracy: 0.951 (+/- 0.0365)


In [ ]:
# 10-fold
scores = cross_val_score(clf, X, y, cv=10, scoring='f1_weighted')
scores

array([0.98237569, 0.90958165, 0.92901849, 0.94708706, 0.98253659,
       0.98236235, 0.92982456, 0.94760977, 0.96520848, 0.96428571])

In [ ]:
print(f"Accuracy: {scores.mean():.3} (+/- {scores.std() * 2:.3})")

Accuracy: 0.954 (+/- 0.0487)


In [ ]:
# Vamos aumentar o desbalanceamento só para tornar o problema mais visível
X['y'] = y

In [ ]:
desbalanceado = X.drop(X[y==0].sample(frac=.9).index)

In [ ]:
desbalanceado.y.value_counts()


1    357
0     21
Name: y, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(desbalanceado.iloc[:,:-1], desbalanceado.iloc[:,-1], test_size=0.3, random_state=42)

In [ ]:
clf = LogisticRegression(C=1.0, max_iter=3000).fit(X_train, y_train)
clf.score(X_test, y_test)

0.9824561403508771

In [ ]:
metrics.f1_score(y_test, clf.predict(X_test))

0.9906542056074766

In [ ]:
clf = svm.SVC(C=1.0).fit(X_train, y_train)
print(clf.score(X_test, y_test))
metrics.f1_score(y_test, clf.predict(X_test))

0.9736842105263158


0.9861751152073733

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, clf.predict(X_test))

array([[  5,   2],
       [  0, 107]])

In [ ]:
clf = DecisionTreeClassifier().fit(X_train, y_train)
print(clf.score(X_test, y_test))
metrics.f1_score(y_test, clf.predict(X_test))

0.9912280701754386


0.9953488372093023

In [ ]:
clf = DecisionTreeClassifier().fit(X_train, y_train)
print(clf.score(X_test, y_test))
metrics.f1_score(y_test, clf.predict(X_test))

1.0


1.0

In [ ]:
clf = RandomForestClassifier().fit(X_train, y_train)
print(clf.score(X_test, y_test))
metrics.f1_score(y_test, clf.predict(X_test))

0.9824561403508771


0.9907407407407407

In [ ]:
np.unique(clf.predict(X_test), return_counts=True)

(array([0, 1]), array([  5, 109]))

In [ ]:
unique, counts = np.unique(clf.predict(X_test), return_counts=True)
print(np.asarray((unique, counts)).T)

[[  0   5]
 [  1 109]]
